### ISSUE TITLE
Support Binary Object Uploads

### ISSUE THREAD

**Issue by RyanAltman** [ballerina-platform/module-ballerinax-aws.s3#17]
**Description:**
Can only `createObject` for textual objects. Would like to upload binary objects with a given media type.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.9.14

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Chuhaa** [comment]
Fixed in https://github.com/ballerina-platform/module-ballerinax-aws.s3/commit/7487776391eb40b62f1a4ddf65598b89b8b88658

**Comment by LakshanSS** [comment]
@Chuhaa Can u close this issue?
